### ISSUE TITLE
Can't add animations to a sequence unless they have matching 'valueCount' template parameters

### ISSUE THREAD

**Issue by sudara** [bgporter/animator#8]
Ok last issue from today for reals! 

I might be missing something here, but it looks like I can't chain two animations together sequentially (for example a fade in and a fade out) unless they have the exact sample `valueCount' template parameter. 

Here's a minimal way to reproduce:

```cpp
auto fadeInParams = std::make_unique<friz::Parametric> (friz::Parametric::CurveType::kEaseOutSine, 0.0f, 1.0f, 0.3f * 60);
auto dropInParams = std::make_unique<friz::Parametric> (friz::Parametric::CurveType::kEaseOutSine, -10.f, 0.f, 0.5f * 60);
auto fadeInTween = std::make_unique<friz::Animation<2>> (friz::Animation<2>::SourceList { std::move (fadeInParams), std::move (dropInParams) }, 0);

auto fadeOutParams = std::make_unique<friz::Parametric> (friz::Parametric::CurveType::kEaseInQuartic, 1.0f, 0.0f, 2.0f * 60);
auto fadeOutTween = std::make_unique<friz::Animation<1>> (friz::Animation<1>::SourceList { std::move (fadeOutParams) }, 0);

auto fadeInThenOutSequence = std::make_unique<friz::Sequence<2>> (0);
fadeInThenOutSequence->AddAnimation (std::move (fadeInTween));
fadeInThenOutSequence->AddAnimation (std::move (fadeOutTween));
```

The error is on the 2nd AddAnimation call, it doesn't like that I'm adding a `friz::Animation<1>` type.

```
No viable conversion from 'unique_ptr<Animation<1>, default_delete<Animation<1>>>' to 'unique_ptr<Animation<2 aka 2>, default_delete<Animation<2>>>'
```

My current workaround is to add a dummy extra AnimatedValue that isn't used.

```
auto fadeOutParams = std::make_unique<friz::Parametric> (friz::Parametric::CurveType::kEaseInQuartic, 1.0f, 0.0f, 2.0f * 60);
auto doNothingParams = std::make_unique<friz::Parametric> (friz::Parametric::CurveType::kEaseInQuartic, 0.0f, 0.0f, 2.0f * 60);
auto fadeOutTween = std::make_unique<friz::Animation<2>> (friz::Animation<2>::SourceList { std::move (fadeOutParams), std::move (doNothingParams) }, 0);
```

I don't know the code well enough to suggest a fix. I'm guessing ideally a sequence shouldn't really care about how many values the animation tween has and should just ask the animations to iterate through them?...

**Comment by sudara** [comment]
Looking at frizDemo, I think my mental model of how sequences work is wrong. 

For the above code, I thought I would be setting `onUpdate` for each tween animation, ala:

```
        fadeInTween->OnUpdate ([&] (int id, const auto& val) {
            juce::AffineTransform t;
            this->setTransform (t.translated (0, val[1]));
            this->setAlpha (val[0]);
        });

        fadeOutTween->SetDelay (4 * 60);
        fadeOutTween->OnUpdate ([&] (int id, const auto& val) {
            this->setAlpha (val[0]);
        });
```

But it looks like when I use a sequence as they are now, I'd have to use the sequence's onUpdate. I think because I just want to chain 2 animations, i'll sidestep sequences for now and use the first animations `onComplete` to run the second.

**Comment by bgporter** [comment]
Note -- v 2.1.0 adds a new `Chain` type that does exactly what you're looking for -- check it out (soon)
